import Head from 'next/head';

export default function MetaData (){
    const staticStylesCss = 'static-styles.css';
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/logo.svg" />
            <link href={staticStylesCss} rel="stylesheet" />
        </Head>
    );
}
